name: healthy
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  google_maps_flutter: ^2.5.0
  file_picker: ^6.1.1
  flutter_switch: ^0.3.2

  #  cloud_firestore: ^4.0.3
  #  firebase_auth: ^4.1.0
  #  firebase_core: ^2.1.1
  #  firebase_storage: ^11.0.3
  firebase_app_check: ^0.2.1+4
  cloud_firestore: ^4.13.0
  firebase_auth: ^4.13.0
  firebase_core: ^2.22.0
  firebase_storage: ^11.5.0
  #  flutter_riverpod: ^2.4.5
  get: ^4.6.6
  loading_indicator: ^3.1.1
  http: ^1.1.0
  connectivity_plus: ^5.0.1
  uuid: ^4.2.1

  permission_handler: ^11.0.1
  image_picker: ^1.0.4
  # flutter_image_compress: ^2.1.0
  firebase_messaging: ^14.7.4
  flutter_local_notifications: ^16.1.0
  intl: ^0.18.1
  flutter_image_compress: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Gotham
      fonts:
        - asset: fonts/Gotham-Black.otf
        - asset: fonts/Gotham-Bold.otf
        - asset: fonts/Gotham-BookItalic.otf
        - asset: fonts/Gotham-Light.otf
        - asset: fonts/Gotham-Thin.otf
        - asset: fonts/Gotham-ThinItalic.otf
        - asset: fonts/Gotham-UltraItalic.otf
        - asset: fonts/Gotham-XLight.otf
        - asset: fonts/Gotham-XLightItalic.otf
        - asset: fonts/GothamBold.ttf
        - asset: fonts/GothamBoldItalic.ttf
        - asset: fonts/GothamBook.ttf
        - asset: fonts/GothamBookItalic.ttf
        - asset: fonts/GothamLight.ttf
        - asset: fonts/GothamLightItalic.ttf
        - asset: fonts/GothamMedium_1.ttf
        - asset: fonts/GothamMedium.ttf
          weight: 500
        - asset: fonts/GothamMediumItalic.ttf
    - family: "Gothm-Medium"
      fonts:
        - asset: fonts/GothamMedium.ttf
          weight: 400
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
